using BettsTax.Core.DTOs.Reports;
using BettsTax.Core.Services.Interfaces;
using BettsTax.Data;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using Microsoft.Extensions.Logging;
using System.Text;
using System.Drawing;

namespace BettsTax.Core.Services;

public class SimpleReportGenerator : IReportGenerator
{
    private readonly ILogger<SimpleReportGenerator> _logger;

    public SimpleReportGenerator(ILogger<SimpleReportGenerator> logger)
    {
        _logger = logger;
        // Note: EPPlus license should be set at application startup in Program.cs
    }

    public async Task<byte[]> GeneratePdfReportAsync(ReportDataDto data, string templateName)
    {
        try
        {
            // For now, return a simple text-based PDF alternative
            var content = GenerateTextReport(data, templateName);
            return Encoding.UTF8.GetBytes(content);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating PDF report with template {TemplateName}", templateName);
            throw;
        }
    }

    public async Task<byte[]> GenerateExcelReportAsync(ReportDataDto data, string templateName)
    {
        try
        {
            using var package = new ExcelPackage();
            var worksheet = package.Workbook.Worksheets.Add(data.Title);

            // Add header with Sierra Leone branding
            AddExcelHeader(worksheet, data);

            // Add content based on template
            await AddExcelContentByTemplate(worksheet, data, templateName);

            // Style the worksheet
            StyleExcelWorksheet(worksheet);

            return package.GetAsByteArray();
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating Excel report with template {TemplateName}", templateName);
            throw;
        }
    }

    public async Task<byte[]> GenerateCsvReportAsync(ReportDataDto data, string templateName)
    {
        try
        {
            var csv = new StringBuilder();
            
            // Add header
            csv.AppendLine($"# {data.Title}");
            csv.AppendLine($"# {data.Subtitle}");
            csv.AppendLine($"# Generated: {data.GeneratedAt:yyyy-MM-dd HH:mm:ss} UTC");
            csv.AppendLine($"# Generated by: {data.GeneratedBy}");
            csv.AppendLine();

            // Add content based on template
            await AddCsvContentByTemplate(csv, data, templateName);

            return Encoding.UTF8.GetBytes(csv.ToString());
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating CSV report with template {TemplateName}", templateName);
            throw;
        }
    }

    private string GenerateTextReport(ReportDataDto data, string templateName)
    {
        var report = new StringBuilder();
        
        // Header
        report.AppendLine("BETTS FIRM - SIERRA LEONE");
        report.AppendLine("=" + new string('=', 50));
        report.AppendLine();
        report.AppendLine(data.Title);
        report.AppendLine("-" + new string('-', data.Title.Length));
        
        if (!string.IsNullOrEmpty(data.Subtitle))
        {
            report.AppendLine(data.Subtitle);
        }
        
        report.AppendLine($"Generated: {data.GeneratedAt:yyyy-MM-dd HH:mm:ss} UTC");
        report.AppendLine($"Generated by: {data.GeneratedBy}");
        report.AppendLine();

        // Content based on template type
        switch (templateName.ToLower())
        {
            case "taxfiling":
                AddTaxFilingTextContent(report, data as TaxFilingReportDataDto);
                break;
            case "paymenthistory":
                AddPaymentHistoryTextContent(report, data as PaymentHistoryReportDataDto);
                break;
            case "compliance":
                AddComplianceTextContent(report, data as ComplianceReportDataDto);
                break;
            case "clientactivity":
                AddClientActivityTextContent(report, data as ClientActivityReportDataDto);
                break;
            default:
                AddGenericTextContent(report, data);
                break;
        }

        return report.ToString();
    }

    private void AddTaxFilingTextContent(StringBuilder report, TaxFilingReportDataDto? data)
    {
        if (data == null) return;

        report.AppendLine("CLIENT INFORMATION");
        report.AppendLine("==================");
        report.AppendLine($"Client Name: {data.ClientName}");
        report.AppendLine($"TIN: {data.TIN}");
        report.AppendLine($"Tax Year: {data.TaxYear}");
        report.AppendLine();

        if (data.Filings.Any())
        {
            report.AppendLine("TAX FILINGS");
            report.AppendLine("===========");
            
            foreach (var filing in data.Filings)
            {
                report.AppendLine($"Tax Type: {filing.TaxTypeName}");
                report.AppendLine($"Filing Date: {filing.FilingDate:yyyy-MM-dd}");
                report.AppendLine($"Due Date: {filing.DueDate:yyyy-MM-dd}");
                report.AppendLine($"Status: {filing.StatusName}");
                report.AppendLine($"Tax Liability: SLE {filing.TaxLiability:N2}");
                report.AppendLine($"Compliance: {filing.ComplianceStatus}");
                report.AppendLine(new string('-', 40));
            }
        }

        AddSummaryText(report, data.Summary);
    }

    private void AddPaymentHistoryTextContent(StringBuilder report, PaymentHistoryReportDataDto? data)
    {
        if (data == null) return;

        report.AppendLine("CLIENT INFORMATION");
        report.AppendLine("==================");
        report.AppendLine($"Client Name: {data.ClientName}");
        report.AppendLine($"TIN: {data.TIN}");
        report.AppendLine($"Period: {data.FromDate:yyyy-MM-dd} to {data.ToDate:yyyy-MM-dd}");
        report.AppendLine();

        if (data.Payments.Any())
        {
            report.AppendLine("PAYMENT HISTORY");
            report.AppendLine("===============");
            
            foreach (var payment in data.Payments)
            {
                report.AppendLine($"Date: {payment.PaymentDate:yyyy-MM-dd}");
                report.AppendLine($"Amount: {payment.FormattedAmount}");
                report.AppendLine($"Method: {payment.MethodName}");
                report.AppendLine($"Status: {payment.StatusName}");
                report.AppendLine($"Tax Type: {payment.TaxTypeName ?? "N/A"}");
                report.AppendLine($"Reference: {payment.Reference}");
                report.AppendLine(new string('-', 40));
            }
        }

        AddSummaryText(report, data.Summary);
    }

    private void AddComplianceTextContent(StringBuilder report, ComplianceReportDataDto? data)
    {
        if (data == null) return;

        report.AppendLine("CLIENT INFORMATION");
        report.AppendLine("==================");
        report.AppendLine($"Client Name: {data.ClientName}");
        report.AppendLine($"TIN: {data.TIN}");
        report.AppendLine($"Period: {data.FromDate:yyyy-MM-dd} to {data.ToDate:yyyy-MM-dd}");
        report.AppendLine($"Overall Compliance Score: {data.OverallComplianceScore:F1}%");
        report.AppendLine($"Compliance Level: {data.ComplianceLevel}");
        report.AppendLine();

        if (data.Items.Any())
        {
            report.AppendLine("COMPLIANCE BREAKDOWN");
            report.AppendLine("===================");
            
            foreach (var item in data.Items)
            {
                report.AppendLine($"Tax Type: {item.TaxTypeName}");
                report.AppendLine($"Total Filings: {item.TotalFilings}");
                report.AppendLine($"On Time: {item.OnTimeFilings}");
                report.AppendLine($"Late: {item.LateFilings}");
                report.AppendLine($"Compliance Rate: {item.ComplianceRate:F1}%");
                report.AppendLine($"Grade: {item.ComplianceGrade}");
                report.AppendLine(new string('-', 40));
            }
        }

        if (data.Penalties.Any())
        {
            report.AppendLine("PENALTIES");
            report.AppendLine("=========");
            
            foreach (var penalty in data.Penalties)
            {
                report.AppendLine($"Date: {penalty.IncurredDate:yyyy-MM-dd}");
                report.AppendLine($"Tax Type: {penalty.TaxTypeName}");
                report.AppendLine($"Reason: {penalty.Reason}");
                report.AppendLine($"Amount: {penalty.FormattedAmount}");
                report.AppendLine($"Paid: {(penalty.IsPaid ? "Yes" : "No")}");
                report.AppendLine(new string('-', 40));
            }
        }

        AddSummaryText(report, data.Summary);
    }

    private void AddClientActivityTextContent(StringBuilder report, ClientActivityReportDataDto? data)
    {
        if (data == null) return;

        report.AppendLine("PERIOD INFORMATION");
        report.AppendLine("==================");
        report.AppendLine($"Period: {data.FromDate:yyyy-MM-dd} to {data.ToDate:yyyy-MM-dd}");
        report.AppendLine($"Total Active Clients: {data.Activities.Count}");
        report.AppendLine();

        if (data.Activities.Any())
        {
            report.AppendLine("CLIENT ACTIVITIES");
            report.AppendLine("================");
            
            foreach (var activity in data.Activities)
            {
                report.AppendLine($"Client: {activity.ClientName}");
                report.AppendLine($"TIN: {activity.TIN}");
                report.AppendLine($"Total Activities: {activity.TotalActivities}");
                report.AppendLine($"Documents: {activity.DocumentsUploaded}");
                report.AppendLine($"Payments: {activity.PaymentsMade}");
                report.AppendLine($"Filings: {activity.TaxFilingsSubmitted}");
                report.AppendLine($"Engagement: {activity.EngagementLevel}");
                report.AppendLine(new string('-', 40));
            }
        }

        AddSummaryText(report, data.Summary);
    }

    private void AddGenericTextContent(StringBuilder report, ReportDataDto data)
    {
        report.AppendLine("REPORT DATA");
        report.AppendLine("===========");

        foreach (var item in data.Data)
        {
            report.AppendLine($"{item.Key}: {item.Value}");
        }
    }

    private void AddSummaryText(StringBuilder report, ReportSummary? summary)
    {
        if (summary == null) return;

        report.AppendLine();
        report.AppendLine("SUMMARY");
        report.AppendLine("=======");
        report.AppendLine($"Total Records: {summary.TotalRecords}");
        
        if (summary.TotalAmount > 0)
        {
            report.AppendLine($"Total Amount: {summary.FormattedTotalAmount}");
        }

        if (summary.Highlights.Any())
        {
            report.AppendLine();
            report.AppendLine("Key Highlights:");
            foreach (var highlight in summary.Highlights)
            {
                report.AppendLine($"• {highlight}");
            }
        }
    }

    private void AddExcelHeader(ExcelWorksheet worksheet, ReportDataDto data)
    {
        worksheet.Cells["A1"].Value = "BETTS FIRM";
        worksheet.Cells["A1"].Style.Font.Bold = true;
        worksheet.Cells["A1"].Style.Font.Size = 16;

        worksheet.Cells["A3"].Value = data.Title;
        worksheet.Cells["A3"].Style.Font.Bold = true;
        worksheet.Cells["A3"].Style.Font.Size = 14;

        worksheet.Cells["A4"].Value = data.Subtitle;
        worksheet.Cells["A5"].Value = $"Generated: {data.GeneratedAt:yyyy-MM-dd HH:mm:ss} UTC";
    }

    private async Task AddExcelContentByTemplate(ExcelWorksheet worksheet, ReportDataDto data, string templateName)
    {
        int row = 7;
        
        switch (templateName.ToLower())
        {
            case "taxfiling":
                row = AddTaxFilingExcelContent(worksheet, data as TaxFilingReportDataDto, row);
                break;
            case "paymenthistory":
                row = AddPaymentHistoryExcelContent(worksheet, data as PaymentHistoryReportDataDto, row);
                break;
            case "compliance":
                row = AddComplianceExcelContent(worksheet, data as ComplianceReportDataDto, row);
                break;
            case "clientactivity":
                row = AddClientActivityExcelContent(worksheet, data as ClientActivityReportDataDto, row);
                break;
            default:
                foreach (var item in data.Data)
                {
                    worksheet.Cells[row, 1].Value = item.Key;
                    worksheet.Cells[row, 2].Value = item.Value?.ToString();
                    row++;
                }
                break;
        }
        
        await Task.CompletedTask;
    }

    private int AddTaxFilingExcelContent(ExcelWorksheet worksheet, TaxFilingReportDataDto? data, int startRow)
    {
        if (data == null) return startRow;

        int row = startRow;
        
        // Client info
        worksheet.Cells[row, 1].Value = "Client Name:";
        worksheet.Cells[row, 2].Value = data.ClientName;
        worksheet.Cells[row, 1].Style.Font.Bold = true;
        row++;
        
        worksheet.Cells[row, 1].Value = "TIN:";
        worksheet.Cells[row, 2].Value = data.TIN;
        worksheet.Cells[row, 1].Style.Font.Bold = true;
        row++;
        
        worksheet.Cells[row, 1].Value = "Tax Year:";
        worksheet.Cells[row, 2].Value = data.TaxYear;
        worksheet.Cells[row, 1].Style.Font.Bold = true;
        row += 2;

        // Filings table
        if (data.Filings.Any())
        {
            worksheet.Cells[row, 1].Value = "Tax Filings";
            worksheet.Cells[row, 1].Style.Font.Bold = true;
            row++;
            
            // Headers
            worksheet.Cells[row, 1].Value = "Tax Type";
            worksheet.Cells[row, 2].Value = "Filing Date";
            worksheet.Cells[row, 3].Value = "Due Date";
            worksheet.Cells[row, 4].Value = "Status";
            worksheet.Cells[row, 5].Value = "Tax Liability";
            worksheet.Cells[row, 6].Value = "Compliance";
            
            using (var range = worksheet.Cells[row, 1, row, 6])
            {
                range.Style.Font.Bold = true;
                range.Style.Fill.PatternType = ExcelFillStyle.Solid;
                range.Style.Fill.BackgroundColor.SetColor(Color.LightBlue);
            }
            row++;

            foreach (var filing in data.Filings)
            {
                worksheet.Cells[row, 1].Value = filing.TaxTypeName;
                worksheet.Cells[row, 2].Value = filing.FilingDate.ToString("yyyy-MM-dd");
                worksheet.Cells[row, 3].Value = filing.DueDate.ToString("yyyy-MM-dd");
                worksheet.Cells[row, 4].Value = filing.StatusName;
                worksheet.Cells[row, 5].Value = $"SLE {filing.TaxLiability:N2}";
                worksheet.Cells[row, 6].Value = filing.ComplianceStatus;
                row++;
            }
        }

        return row;
    }

    private int AddPaymentHistoryExcelContent(ExcelWorksheet worksheet, PaymentHistoryReportDataDto? data, int startRow)
    {
        if (data == null) return startRow;

        int row = startRow;
        
        // Client info
        worksheet.Cells[row, 1].Value = "Client Name:";
        worksheet.Cells[row, 2].Value = data.ClientName;
        worksheet.Cells[row, 1].Style.Font.Bold = true;
        row++;
        
        worksheet.Cells[row, 1].Value = "Period:";
        worksheet.Cells[row, 2].Value = $"{data.FromDate:yyyy-MM-dd} to {data.ToDate:yyyy-MM-dd}";
        worksheet.Cells[row, 1].Style.Font.Bold = true;
        row += 2;

        // Payments table
        if (data.Payments.Any())
        {
            worksheet.Cells[row, 1].Value = "Payment History";
            worksheet.Cells[row, 1].Style.Font.Bold = true;
            row++;
            
            // Headers
            worksheet.Cells[row, 1].Value = "Date";
            worksheet.Cells[row, 2].Value = "Amount";
            worksheet.Cells[row, 3].Value = "Method";
            worksheet.Cells[row, 4].Value = "Status";
            worksheet.Cells[row, 5].Value = "Tax Type";
            worksheet.Cells[row, 6].Value = "Reference";
            
            using (var range = worksheet.Cells[row, 1, row, 6])
            {
                range.Style.Font.Bold = true;
                range.Style.Fill.PatternType = ExcelFillStyle.Solid;
                range.Style.Fill.BackgroundColor.SetColor(Color.LightBlue);
            }
            row++;

            foreach (var payment in data.Payments)
            {
                worksheet.Cells[row, 1].Value = payment.PaymentDate.ToString("yyyy-MM-dd");
                worksheet.Cells[row, 2].Value = payment.FormattedAmount;
                worksheet.Cells[row, 3].Value = payment.MethodName;
                worksheet.Cells[row, 4].Value = payment.StatusName;
                worksheet.Cells[row, 5].Value = payment.TaxTypeName ?? "N/A";
                worksheet.Cells[row, 6].Value = payment.Reference;
                row++;
            }
        }

        return row;
    }

    private int AddComplianceExcelContent(ExcelWorksheet worksheet, ComplianceReportDataDto? data, int startRow)
    {
        if (data == null) return startRow;
        // Implementation similar to other methods
        return startRow + 10; // Simplified for now
    }

    private int AddClientActivityExcelContent(ExcelWorksheet worksheet, ClientActivityReportDataDto? data, int startRow)
    {
        if (data == null) return startRow;
        // Implementation similar to other methods
        return startRow + 10; // Simplified for now
    }

    private void StyleExcelWorksheet(ExcelWorksheet worksheet)
    {
        worksheet.Cells[worksheet.Dimension.Address].AutoFitColumns();
        
        // Add some basic styling
        using (var range = worksheet.Cells["A1:B1"])
        {
            range.Style.Fill.PatternType = ExcelFillStyle.Solid;
            range.Style.Fill.BackgroundColor.SetColor(Color.FromArgb(41, 128, 185)); // Sierra Blue
            range.Style.Font.Color.SetColor(Color.White);
        }
    }

    private async Task AddCsvContentByTemplate(StringBuilder csv, ReportDataDto data, string templateName)
    {
        switch (templateName.ToLower())
        {
            case "taxfiling":
                AddTaxFilingCsvContent(csv, data as TaxFilingReportDataDto);
                break;
            case "paymenthistory":
                AddPaymentHistoryCsvContent(csv, data as PaymentHistoryReportDataDto);
                break;
            default:
                csv.AppendLine("Key,Value");
                foreach (var item in data.Data)
                {
                    csv.AppendLine($"\"{item.Key}\",\"{item.Value}\"");
                }
                break;
        }
        
        await Task.CompletedTask;
    }

    private void AddTaxFilingCsvContent(StringBuilder csv, TaxFilingReportDataDto? data)
    {
        if (data == null) return;

        csv.AppendLine("Tax Type,Filing Date,Due Date,Status,Tax Liability,Compliance Status");
        
        foreach (var filing in data.Filings)
        {
            csv.AppendLine($"\"{filing.TaxTypeName}\",\"{filing.FilingDate:yyyy-MM-dd}\",\"{filing.DueDate:yyyy-MM-dd}\",\"{filing.StatusName}\",\"SLE {filing.TaxLiability:N2}\",\"{filing.ComplianceStatus}\"");
        }
    }

    private void AddPaymentHistoryCsvContent(StringBuilder csv, PaymentHistoryReportDataDto? data)
    {
        if (data == null) return;

        csv.AppendLine("Date,Amount,Method,Status,Tax Type,Reference");
        
        foreach (var payment in data.Payments)
        {
            csv.AppendLine($"\"{payment.PaymentDate:yyyy-MM-dd}\",\"{payment.FormattedAmount}\",\"{payment.MethodName}\",\"{payment.StatusName}\",\"{payment.TaxTypeName ?? "N/A"}\",\"{payment.Reference}\"");
        }
    }
}