'use client';

import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Separator } from '@/components/ui/separator';
import { 
  Download, 
  Eye, 
  FileText, 
  BarChart3,
  PieChart,
  TrendingUp,
  Calendar,
  User,
  Building,
  DollarSign,
  AlertCircle,
  CheckCircle,
  Clock,
  Printer,
  Share2,
  Maximize2,
  ZoomIn,
  ZoomOut,
  RotateCcw
} from 'lucide-react';
import { format } from 'date-fns';
import { useToast } from '@/components/ui/use-toast';
import { ReportRequest, reportService } from '@/lib/services/report-service';
import { getNumericDefault, getStringDefault, getArrayDefault } from '@/lib/utils/data-defaults';
import { Skeleton } from '@/components/ui/skeleton';

interface ReportPreviewProps {
  report: ReportRequest;
  onClose: () => void;
  onDownload?: (reportId: string, title: string) => void;
}

export default function ReportPreview({ report, onClose, onDownload }: ReportPreviewProps) {
  const { toast } = useToast();
  const [activeTab, setActiveTab] = useState('preview');
  const [zoomLevel, setZoomLevel] = useState(100);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    // Refresh report status to get latest data
    const refreshReport = async () => {
      if (report.status === 'Completed' || report.status === 'Processing') {
        setLoading(true);
        setError(null);
        try {
          const updatedReport = await reportService.getReport(report.id);
          if (!updatedReport.success) {
            setError(updatedReport.error || 'Failed to load report data');
          }
        } catch (err) {
          console.error('Error refreshing report:', err);
          setError(err instanceof Error ? err.message : 'Failed to load report data');
        } finally {
          setLoading(false);
        }
      }
    };

    refreshReport();
  }, [report.id, report.status]);

  const handleDownload = () => {
    if (onDownload) {
      onDownload(report.id, report.title);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const handleShare = () => {
    if (navigator.share) {
      navigator.share({
        title: report.title,
        text: report.description || 'Report generated by Sierra Leone CTIS',
        url: window.location.href,
      });
    } else {
      navigator.clipboard.writeText(window.location.href);
      toast({
        title: 'Link Copied',
        description: 'Report link has been copied to clipboard.',
      });
    }
  };



  return (
    <div className="space-y-6">
      {/* Header */}
      <Card>
        <CardHeader>
          <div className="flex items-start justify-between">
            <div>
              <CardTitle className="flex items-center gap-2">
                <FileText className="h-5 w-5" />
                {report.title}
              </CardTitle>
              <CardDescription className="mt-2">
                {report.description || `${report.reportType} report generated on ${format(new Date(report.createdAt), 'PPP')}`}
              </CardDescription>
            </div>
            <Badge className="ml-4">
              {report.status}
            </Badge>
          </div>
        </CardHeader>
      </Card>

      {/* Action Bar */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" onClick={() => setZoomLevel(Math.max(50, zoomLevel - 10))}>
            <ZoomOut className="h-4 w-4" />
          </Button>
          <span className="text-sm text-muted-foreground">{zoomLevel}%</span>
          <Button variant="outline" size="sm" onClick={() => setZoomLevel(Math.min(200, zoomLevel + 10))}>
            <ZoomIn className="h-4 w-4" />
          </Button>
          <Button variant="outline" size="sm" onClick={() => setZoomLevel(100)}>
            <RotateCcw className="h-4 w-4" />
          </Button>
        </div>
        
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" onClick={handleShare}>
            <Share2 className="h-4 w-4" />
          </Button>
          <Button variant="outline" size="sm" onClick={handlePrint}>
            <Printer className="h-4 w-4" />
          </Button>
          {report.status === 'Completed' && (
            <Button size="sm" onClick={handleDownload}>
              <Download className="mr-2 h-4 w-4" />
              Download
            </Button>
          )}
        </div>
      </div>

      {/* Preview Content */}
      <Tabs value={activeTab} onValueChange={setActiveTab}>
        <TabsList>
          <TabsTrigger value="preview">Preview</TabsTrigger>
          <TabsTrigger value="details">Details</TabsTrigger>
          <TabsTrigger value="metadata">Metadata</TabsTrigger>
        </TabsList>

        <TabsContent value="preview" className="space-y-6">
          <div style={{ transform: `scale(${zoomLevel / 100})`, transformOrigin: 'top left' }}>
            {loading ? (
              <Card>
                <CardContent className="p-8">
                  <div className="text-center">
                    <Skeleton className="h-8 w-8 mx-auto mb-4" />
                    <Skeleton className="h-4 w-48 mx-auto" />
                    <p className="text-muted-foreground mt-4">Loading report preview...</p>
                  </div>
                </CardContent>
              </Card>
            ) : error ? (
              <Alert variant="destructive">
                <AlertCircle className="h-4 w-4" />
                <AlertDescription>
                  {error}
                </AlertDescription>
              </Alert>
            ) : report.status === 'Completed' ? (
              <Card>
                <CardContent className="p-8">
                  <div className="text-center">
                    <FileText className="h-16 w-16 mx-auto mb-4 text-sierra-blue-600" />
                    <h3 className="text-lg font-medium mb-2">{report.reportType} Report</h3>
                    <p className="text-muted-foreground mb-4">
                      This report has been completed. Download the full report to view detailed data and analysis.
                    </p>
                    {report.downloadUrl && (
                      <div className="mt-4">
                        <Button onClick={handleDownload}>
                          <Download className="mr-2 h-4 w-4" />
                          Download Report
                        </Button>
                      </div>
                    )}
                    <div className="text-sm text-muted-foreground mt-6">
                      <p>Report ID: {report.id}</p>
                      <p>Generated: {format(new Date(report.createdAt), 'PPP pp')}</p>
                      {report.completedAt && (
                        <p>Completed: {format(new Date(report.completedAt), 'PPP pp')}</p>
                      )}
                      {report.fileSize && (
                        <p>File Size: {(report.fileSize / 1024 / 1024).toFixed(2)} MB</p>
                      )}
                    </div>
                  </div>
                </CardContent>
              </Card>
            ) : report.status === 'Processing' ? (
              <Card>
                <CardContent className="p-8">
                  <div className="text-center">
                    <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-sierra-blue-600 mx-auto mb-4"></div>
                    <h3 className="text-lg font-medium mb-2">Report Processing</h3>
                    <p className="text-muted-foreground mb-4">
                      Your report is currently being generated. Preview will be available once processing is complete.
                    </p>
                    <div className="w-full bg-gray-200 rounded-full h-2.5 mb-4">
                      <div 
                        className="bg-sierra-blue-600 h-2.5 rounded-full transition-all duration-300" 
                        style={{ width: `${getNumericDefault(report.progress)}%` }}
                      ></div>
                    </div>
                    <p className="text-sm text-muted-foreground">
                      Progress: {getNumericDefault(report.progress)}%
                    </p>
                  </div>
                </CardContent>
              </Card>
            ) : report.status === 'Failed' ? (
              <Alert variant="destructive">
                <AlertCircle className="h-4 w-4" />
                <AlertDescription>
                  <div className="font-medium mb-2">Report Generation Failed</div>
                  {report.errorMessage ? (
                    <p>{report.errorMessage}</p>
                  ) : (
                    <p>An error occurred while generating this report. Please try generating a new report.</p>
                  )}
                </AlertDescription>
              </Alert>
            ) : (
              <Card>
                <CardContent className="p-8">
                  <div className="text-center">
                    <Clock className="h-16 w-16 mx-auto mb-4 text-muted-foreground" />
                    <h3 className="text-lg font-medium mb-2">{report.reportType} Report</h3>
                    <p className="text-muted-foreground mb-4">
                      This report is pending generation. Preview will be available once processing begins.
                    </p>
                    <div className="text-sm text-muted-foreground">
                      <p>Status: {getStringDefault(report.status)}</p>
                      <p>Created: {format(new Date(report.createdAt), 'PPP pp')}</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            )}
          </div>
        </TabsContent>

        <TabsContent value="details" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Report Information</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <div className="font-medium">Report Type</div>
                  <div className="text-sm text-muted-foreground">{report.reportType}</div>
                </div>
                <div>
                  <div className="font-medium">Status</div>
                  <div className="text-sm text-muted-foreground">{report.status}</div>
                </div>
                <div>
                  <div className="font-medium">Created</div>
                  <div className="text-sm text-muted-foreground">
                    {format(new Date(report.createdAt), 'PPP pp')}
                  </div>
                </div>
                {report.completedAt && (
                  <div>
                    <div className="font-medium">Completed</div>
                    <div className="text-sm text-muted-foreground">
                      {format(new Date(report.completedAt), 'PPP pp')}
                    </div>
                  </div>
                )}
                {report.fileSize && (
                  <div>
                    <div className="font-medium">File Size</div>
                    <div className="text-sm text-muted-foreground">
                      {(report.fileSize / 1024 / 1024).toFixed(2)} MB
                    </div>
                  </div>
                )}
                <div>
                  <div className="font-medium">User ID</div>
                  <div className="text-sm text-muted-foreground">{report.userId}</div>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="metadata" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Parameters & Configuration</CardTitle>
            </CardHeader>
            <CardContent>
              {report.parameters && Object.keys(report.parameters).length > 0 ? (
                <div className="space-y-3">
                  {Object.entries(report.parameters).map(([key, value]) => (
                    <div key={key} className="flex justify-between">
                      <span className="font-medium capitalize">{key.replace(/([A-Z])/g, ' $1').trim()}</span>
                      <span className="text-muted-foreground">
                        {typeof value === 'boolean' ? (value ? 'Yes' : 'No') : String(value)}
                      </span>
                    </div>
                  ))}
                </div>
              ) : (
                <p className="text-muted-foreground">No parameters configured for this report.</p>
              )}
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}